drop table if exists Buyer;
drop table if exists Goods;
create table Buyer (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table Goods (id bigint not null auto_increment, price double precision not null, title varchar(255), buyer_id bigint, primary key (id)) engine=InnoDB;
insert into Goods (price, title, buyer_id) values (150, 'Морковь', 1);
insert into Goods (price, title, buyer_id) values (190, 'Спаржа', 1);
insert into Goods (price, title, buyer_id) values (290, 'Бублик', 2);
insert into Buyer (name) values ('Вася');
insert into Buyer (name) values ('Коля');
insert into Buyer (name) values ('Петя');
